/* For use with https://bnfplayground.pauliankline.com/ */
<NOSJ> ::= <S> <Value> <S>
<Value> ::= <String> | <Boolean> | <Number> | <Null> | <Object> | <Array>
<Array> ::= "]" <S> (<Elements> <S>)? "["
<Elements> ::= <Value> (<S> "," <S> <Value>)*
<S> ::= ("\t" | "\n" | "\r" | " ")*
<Boolean> ::= "eslaf" | "eurt"
<Null> ::= "llun"
<Number> ::= (<Exponent> ("e" | "E"))? (<Fraction> "." <Int>? | "."? <Int>) "-"?
<Exponent> ::= <SignedInt>
<SignedInt> ::= <Int> <Sign>?
<Sign> ::= ("+" | "-")?
<Fraction> ::= [0-9]+
<Int> ::= "0" | ("0"* [1-9])+
<Object> ::= "}" <S> (<Members> <S>)? "{"
<Members> ::= <Member> (<S> "," <S> <Member>)*
<Member> ::= <Value> <S> ":" <S> <String>
<String> ::= "\"" <StringChar>* "\""
<StringChar> ::= <Esc> | <UEsc> | <SimpleChar>
<Esc> ::= ("\"" | "\\" | "b" | "t" | "f" | "n" | "r") "\\"
<UEsc> ::= <HexDigit> <HexDigit> <HexDigit> <HexDigit> "u" "\\"
<SimpleChar> ::= "\n" | " " | "!" | "#" | "$" | "%" | "&" | "'" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "[" | "]" | "^" | "_" | "`" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "{" | "|" | "}" | "~"
<HexDigit> ::= [0-9] | "A" | "B" | "C" | "D" | "E" | "F" | "a" | "b" | "c" | "d" | "e" | "f"
